export const DOCUMENTATION = [
  {title:'What Quant Edge does',text:'Quant Edge is a long-only Indian cash-equity research platform. Configure a strategy, run a backtest, inspect net performance and trades, then compare, save or export. It does not place live orders. Backtested performance does not guarantee future results.'},
  {title:'Demo versus real data',text:'DEMO / SYNTHETIC uses a deterministic seeded price generator. It is not historical market performance. Its sequence restarts at the requested start date and includes weekdays without exchange-holiday filtering. REAL HISTORICAL DATA uses configured Kite Connect instruments and credentials on the server. Failed real-data requests never fall back to synthetic candles. Reports include requested/actual dates, provider, exchange, daily timeframe and a SHA-256 data fingerprint.'},
  {title:'Execution chronology',text:'Signals use data through the current close and execute at the next bar open. First warmup values cannot trigger retrospective entries. Each bar processes existing-position gaps, pending strategy exits, eligible entries, then intrabar protective exits. If both stop and target are touched, the stop wins. Gap exits fill at the available open. Trailing stops rise only after the current bar’s exit decision and apply from the next bar. End-of-period liquidation uses the last close. Intraday mode closes at every daily close; this approximates session liquidation and cannot reproduce the broker’s exact square-off time.'},
  {title:'Sizing and cash',text:'Capital % uses available cash; Fixed Quantity requests whole units; Risk % divides the available-cash risk budget by the initial fixed stop distance. Charges and an exit-cost reserve reduce affordable quantity. Gaps, slippage and charges can exceed the nominal risk budget. Multiple lots of the same instrument are supported, with independent risk exits. Strategy exits close all lots. Allocation limits use prior-close portfolio equity and existing entry-price cost basis, excluding charges. The start-of-bar position count controls entry eligibility; intrabar exits never retrospectively fund an opening entry. Cash plus marked open positions forms net equity.'},
  {title:'Indian costs',text:'Zero Costs, Zerodha Equity Intraday, Zerodha Equity Delivery and Custom Costs are supported. Brokerage, STT, exchange, SEBI, IPFT, GST, stamp duty and DP are separate. Zerodha current resident-individual rates were verified on 20 September 2026. DP applies once per symbol/date for overnight selling, including BTST; same-day delivery round trips use intraday charges. GST applies to taxable service charges, including DP. Slippage worsens entry and exit fill prices once. Gross P&L already includes slippage; net P&L subtracts charges. Presets estimate charges per simulated order with whole-rupee STT rounding; contract-note aggregation and settlement exceptions can differ. Current tariffs are applied over the whole range, not reconstructed historical tariffs. See README for official rate sources and exclusions.'},
  {title:'Performance and risk methodology',text:'Total return is ending net equity / initial capital − 1. CAGR uses elapsed calendar days / 365.2425. Sharpe uses the mean daily excess return divided by sample daily standard deviation, annualized by √252. Annual risk-free rate is converted to a compound daily rate. Sortino uses the square root of the mean squared negative excess returns across all periods, annualized by √252. Volatility uses sample standard deviation × √252. Missing sessions are not invented; these ratios assume the supplied daily observations represent trading sessions. N/A is used for undefined denominators, no-trade ratios and insufficient data.'},
  {title:'Drawdown and monthly returns',text:'Drawdown is measured from running equity peaks. Peak/trough/recovery dates refer to the maximum percentage drawdown episode; the maximum rupee decline is computed independently. Duration runs from peak to first recovery or the final observation if unrecovered. Longest recovery includes ongoing drawdowns. Monthly returns use actual month-end equity against the previous month end; the first month starts from initial capital. No return is spread artificially across months.'},
  {title:'Trade statistics and exposure',text:'Wins and losses use net trade P&L; breakeven trades are counted separately. Profit factor is sum of positive net trade P&L divided by absolute negative net trade P&L, and is N/A when there are no losses. Expectancy is average net trade P&L. Risk/reward is average winning trade divided by absolute average losing trade. Holding periods are calendar days. Exposure is the fraction of supplied sessions with any lot held during that session, including entry/exit days. Turnover is executed buy plus sell notional. Charges exclude slippage because slippage is already reflected in fills.'},
  {title:'Comparison and exports',text:'Compare up to four completed runs. Curves show return on each run’s initial capital; missing dates remain gaps. Different instruments, datasets or date ranges generate a comparability warning. No strategy is declared best. CSV exports use current trade data, component costs and synthetic/real labels, with formula-injection protection. Summary JSON includes the current configuration, metrics and provenance.'},
  {title:'Saving and accounts',text:'Browser saves need no credentials, are limited to 100 summaries and are visible to anyone using that browser profile. Do not use shared browser storage for private research. Optional Supabase accounts support email/password sign-in and registration, HTTP-only session cookies and owner-scoped PostgreSQL row security. Cloud saving reruns the configuration on the server; client-reported performance and user IDs are not trusted. Reopening restores settings, not an archived candle dataset. Re-running may differ if the provider revises data. Sessions expire after at most one hour; sign in again to continue. Configure Supabase email delivery and confirmation before inviting users.'},
  {title:'Limits and known omissions',text:'This milestone supports daily candles, long positions, one instrument per run, at most 20 concurrent lots, 4,000 candles and ten years. No shorts, leverage, multi-instrument portfolios, dividends, independent split adjustment, exchange price-band liquidity, partial fills, settlement-delay cash blocking, auction handling or intraday timestamps. BSE special scrip groups require custom charges. Real-provider terms must permit the intended use; an API subscription is not permission to redistribute datasets. Broker charges are estimates, not contract notes. No live payment subscription is offered.'},
];
