import type { DocumentSection } from "@/components/document-page";

export const RELEASE_DATE = "20 September 2026";

export const TERMS_SECTIONS: DocumentSection[] = [
  {title:"Acceptance of Terms",paragraphs:["By accessing or using Quant Edge, you agree to these Terms of Use. If you do not agree, do not use the project."]},
  {title:"Eligibility",paragraphs:["You must be legally capable of accepting these terms in your jurisdiction. If you use Quant Edge for an organisation, you represent that you are authorised to act for it."]},
  {title:"Description of Quant Edge",paragraphs:["Quant Edge is an independent software and quantitative-finance portfolio project that demonstrates strategy configuration, hypothetical backtesting, risk controls, transaction-cost modelling, analytics and reporting."]},
  {title:"Portfolio, educational and research purpose",paragraphs:["The project is presented for software demonstration, education and research. It is not currently offered as a commercial trading, advisory, brokerage or portfolio-management service."]},
  {title:"No investment advice",paragraphs:["Nothing in Quant Edge is investment, financial, legal, accounting or tax advice. Outputs are generated from user-selected assumptions and must not be treated as guidance tailored to any person."]},
  {title:"No research-analyst recommendation",paragraphs:["Quant Edge does not publish or hold itself out as providing a SEBI-registered research-analyst recommendation. Strategy names and outputs are technical demonstrations, not buy, sell or hold calls."]},
  {title:"No brokerage or trade execution",paragraphs:["Quant Edge does not accept orders, connect the portfolio release to brokerage accounts, custody assets or execute transactions."]},
  {title:"No portfolio-management service",paragraphs:["Quant Edge does not manage funds, securities, portfolios or accounts for users."]},
  {title:"No fiduciary relationship",paragraphs:["Use of the project does not create an adviser-client, fiduciary, agency, partnership, employment or other professional relationship with Isaac Silveira."]},
  {title:"No offer or solicitation",paragraphs:["Nothing displayed by Quant Edge is an offer, invitation or solicitation to buy, sell, subscribe for or otherwise transact in a security or financial product."]},
  {title:"Synthetic demonstration data",paragraphs:["The portfolio release uses deterministic synthetic market data. It does not provide actual historical NSE or BSE performance, and demo instrument names do not represent tradable securities or indices."]},
  {title:"Hypothetical backtesting",paragraphs:["Backtests are simulations based on coded rules and assumptions. They do not record actual trading, and no represented account achieved the displayed results."]},
  {title:"Backtesting limitations",paragraphs:["Hypothetical results can be affected by model design, parameter selection, overfitting, incomplete data, survivorship and look-ahead bias, corporate actions, liquidity, market impact and assumptions about fills. Simulation cannot fully reproduce live markets."]},
  {title:"User responsibility",paragraphs:["You are responsible for evaluating outputs, verifying assumptions and obtaining qualified advice before making financial decisions. Do not rely on Quant Edge as the sole basis for any decision."]},
  {title:"Financial and market risk",paragraphs:["Trading and investing can result in partial or total loss of capital. Volatility, gaps, liquidity constraints, operational failures and changing market conditions can produce outcomes materially different from a backtest."]},
  {title:"Transaction-cost assumptions",paragraphs:["Brokerage, taxes, statutory charges, exchange charges, DP fees and slippage are modelling assumptions. They may be incomplete, become outdated or differ from an actual broker contract note and a user’s tax circumstances."]},
  {title:"Data accuracy and limitations",paragraphs:["Quant Edge does not warrant that any dataset, configuration, calculation or output is complete, error-free, current or suitable for a particular purpose. Synthetic data is designed to exercise software behavior, not recreate a particular market history."]},
  {title:"Third-party services and links",paragraphs:["Links and optional infrastructure may lead to services controlled by third parties. Their availability, security, content and terms are their responsibility. A link does not imply endorsement."]},
  {title:"Intellectual property",paragraphs:["Quant Edge’s original software, interface, text and branding are protected by applicable intellectual-property law. The public source repository and any included third-party components remain subject to their respective licence terms and notices."]},
  {title:"Acceptable use",paragraphs:["You may use the project lawfully for portfolio review, education, research and software evaluation, subject to these terms and applicable third-party rights."]},
  {title:"Prohibited misuse",bullets:["Do not use Quant Edge for unlawful, fraudulent or deceptive activity.","Do not attempt unauthorised access, disrupt service, evade limits, introduce malicious code or probe other users’ information.","Do not present synthetic outputs as actual market performance or imply that Quant Edge supplies regulated advice, guaranteed returns or trade execution.","Do not infringe intellectual-property, privacy, data-licensing or other third-party rights."]},
  {title:"Availability and service changes",paragraphs:["Features, datasets, limits and access may be corrected, changed, suspended or discontinued as the portfolio project evolves."]},
  {title:"No guarantee of uptime",paragraphs:["Continuous, timely, secure or error-free availability is not guaranteed. Maintenance, hosting failures and third-party outages may interrupt access."]},
  {title:"Disclaimer of warranties",paragraphs:["Quant Edge is provided “as is” and “as available.” To the maximum extent permitted by applicable law, all implied warranties, including merchantability, fitness for a particular purpose, accuracy and non-infringement, are disclaimed."]},
  {title:"Limitation of liability",paragraphs:["To the maximum extent permitted by applicable law, Isaac Silveira will not be liable for indirect, incidental, special, consequential or punitive loss, loss of profits or data, trading loss, or decisions made using the project. Nothing in these terms excludes liability that applicable law does not permit to be excluded."]},
  {title:"Indemnification",paragraphs:["To the extent permitted by applicable law, you agree to indemnify and hold Isaac Silveira harmless from third-party claims and reasonable costs arising from your unlawful misuse of Quant Edge or material breach of these terms."]},
  {title:"Termination and access restriction",paragraphs:["Access may be restricted or terminated where reasonably necessary to protect the project, users, infrastructure or legal rights, including in response to misuse or a breach of these terms."]},
  {title:"Changes to these Terms",paragraphs:["These terms may be updated when the project or applicable requirements change. The effective and last-updated date identifies the current version. Continued use after publication of an update constitutes acceptance where permitted by law."]},
  {title:"Severability",paragraphs:["If a provision is held invalid or unenforceable, it will be limited to the minimum extent necessary and the remaining provisions will continue in effect."]},
  {title:"Entire agreement",paragraphs:["These Terms, together with the Privacy Policy, Financial Disclaimer and Risk Disclosure, form the entire agreement concerning use of this portfolio release, except where applicable law requires otherwise."]},
  {title:"Governing law",paragraphs:["These terms are governed by the laws of India, without prejudice to mandatory rights that apply in your jurisdiction. Disputes will be subject to the competent courts in India, to the extent permitted by applicable law."]},
];

export const PRIVACY_SECTIONS: DocumentSection[] = [
  {title:"Scope",paragraphs:["This policy explains information processed when you visit or use the Quant Edge portfolio project. It distinguishes browser-local operation from optional cloud-account functionality."]},
  {title:"Information you provide",paragraphs:["Backtest settings, labels and other configuration values you enter are processed to run and display the requested simulation. The portfolio release does not ask for brokerage credentials, payment details or investment-account information."]},
  {title:"Browser and local storage",paragraphs:["Theme preference and locally saved backtest settings, summaries and provenance are stored in your browser using localStorage. These records remain visible to anyone with access to the same browser profile. Quant Edge does not store candle datasets in local history."]},
  {title:"Backtest processing",paragraphs:["Backtest configurations are sent to the application server for validation and calculation. API responses include reports, trades, analytics and provenance but omit the source candle array. Ordinary hosting infrastructure may process request metadata such as IP address, time, route, device or browser information and diagnostic logs."]},
  {title:"Cookies",paragraphs:["The default browser-local experience does not require an account cookie. If optional Supabase accounts are enabled and you sign in, Quant Edge uses a secure-in-production, HTTP-only, SameSite=Strict session cookie with a maximum lifetime of one hour."]},
  {title:"Optional Supabase accounts",paragraphs:["When configured by the operator, Supabase processes the email address, password authentication and cloud-saved backtest records needed for account functionality. Passwords are submitted to Supabase Auth and are not stored in Quant Edge’s application code. Cloud records are designed to be restricted to their verified owner through row-level security."]},
  {title:"Analytics and advertising",paragraphs:["No product-analytics, behavioural-advertising or advertising SDK is present in this release. Hosting providers may still generate operational logs according to their configuration and policies."]},
  {title:"Purposes",bullets:["Run and display requested backtests.","Save and reopen local or, when enabled, owner-scoped cloud records.","Remember the selected visual theme.","Protect, debug and operate the application.","Comply with applicable legal obligations."]},
  {title:"Service providers",paragraphs:["Vercel may host the deployed application and process network and operational data. Supabase is used only when optional cloud accounts are configured. External GitHub and documentation links are governed by their own privacy practices."]},
  {title:"Retention",paragraphs:["Local records remain until you delete them through the interface or clear browser storage. A session cookie expires after at most one hour. Optional cloud records remain until deleted or until the configured Supabase project applies its retention policy. Hosting and security logs may be retained by infrastructure providers for their operational periods."]},
  {title:"Security",paragraphs:["Quant Edge uses server-side validation, bounded requests, same-origin checks on mutations, restrictive cookies, security headers and owner-scoped cloud access controls. No internet service can guarantee absolute security."]},
  {title:"Your choices",paragraphs:["You may use the project without cloud accounts, delete local saves, clear localStorage and cookies, delete individual cloud saves when signed in, or stop using the service. Browser and hosting controls may provide additional choices."]},
  {title:"Children",paragraphs:["Quant Edge is not directed to children and does not intentionally solicit children’s personal data."]},
  {title:"Indian privacy principles",paragraphs:["Information should be processed for stated, proportionate purposes and protected with reasonable safeguards. This policy does not claim certification, government approval or a determination of compliance by any regulator."]},
  {title:"Policy updates",paragraphs:["This policy may change when functionality, infrastructure or applicable requirements change. The date above identifies the current version."]},
];

export const DISCLAIMER_SECTIONS: DocumentSection[] = [
  {title:"Software and portfolio project",paragraphs:["Quant Edge is software created as an independent quantitative-finance and engineering portfolio project. It demonstrates backtesting concepts and does not provide a regulated financial service."]},
  {title:"No advice or recommendations",paragraphs:["Quant Edge does not provide investment or personalised financial advice, stock recommendations, brokerage, trade execution or money management. It is not presented as a SEBI-registered Investment Adviser or Research Analyst."]},
  {title:"Synthetic data",paragraphs:["The v1.0 portfolio release uses deterministic synthetic demonstration datasets. Synthetic results are not historical NSE or BSE results and should never be represented as the performance of a real security, index, account or strategy."]},
  {title:"Hypothetical performance",paragraphs:["Backtested results are hypothetical. Past performance does not guarantee future performance, and no strategy is guaranteed to generate profits or avoid losses."]},
  {title:"Why live results differ",bullets:["Survivorship, look-ahead and parameter-selection bias can overstate results.","Data errors, missing sessions, symbol changes and corporate actions can alter signals and returns.","Slippage, liquidity, market impact, taxes, transaction costs and price gaps may be worse than modelled.","Orders may be rejected, delayed, partially filled or unfilled.","Execution assumptions and end-of-day bars cannot reproduce intraday market paths.","Market structure, volatility, correlations and strategy effectiveness change over time."]},
  {title:"User judgment",paragraphs:["You remain solely responsible for independent verification and financial decisions. Consider advice from appropriately qualified professionals where needed."]},
];

export const RISK_SECTIONS: DocumentSection[] = [
  {title:"Loss of capital",paragraphs:["Trading and investing can cause substantial losses, including total loss of committed capital. A backtest cannot establish that a strategy is safe."]},
  {title:"Volatility, drawdown and gap risk",paragraphs:["Prices can move quickly, remain below prior peaks for long periods, or gap through intended stops. Actual losses can exceed a configured risk percentage or stop distance."]},
  {title:"Liquidity and execution risk",paragraphs:["Available volume, spreads, queue position, market impact, halts, price bands and rejected or partial orders can prevent execution at a modelled price."]},
  {title:"Model and strategy risk",paragraphs:["A coded rule may contain assumptions, defects or simplifications. A historically or synthetically successful strategy can stop working, concentrate risk or behave unexpectedly."]},
  {title:"Data and corporate-action risk",paragraphs:["Missing, inaccurate, stale or unadjusted data can distort indicators and performance. Splits, bonuses, dividends, mergers, demergers, delistings and symbol changes require careful treatment."]},
  {title:"Overfitting and optimization bias",paragraphs:["Repeatedly selecting parameters after observing results can fit noise rather than a durable relationship. Strong in-sample performance may fail out of sample."]},
  {title:"Changing market regimes",paragraphs:["Trends, volatility, liquidity, regulation, fees and participant behavior change. Relationships encoded by a strategy may weaken or reverse."]},
  {title:"Technology and operational risk",paragraphs:["Software defects, network outages, infrastructure failure, configuration errors, security incidents and third-party service interruptions can affect access or results."]},
  {title:"Simulation versus trading",paragraphs:["Quant Edge’s daily-bar simulation cannot reproduce order-book dynamics, intraday sequencing, emotional pressures or every operational constraint of actual trading."]},
  {title:"Your responsibility",paragraphs:["You are responsible for understanding these risks, testing assumptions independently and deciding whether any real-world activity is appropriate. Quant Edge does not make that decision for you."]},
];
