import { BacktestResult } from "@/lib/types";
import { formatCurrency, formatDate, formatNumber, formatPct } from "@/lib/format";
import { COST_PRESETS } from "@/lib/costs/presets";

function DetailGroup({ title, rows }: { title: string; rows: Array<[string, string]> }) {
  return <div><h3 className="text-xs font-bold uppercase tracking-[.08em] text-slate-500">{title}</h3><dl className="mt-3 grid gap-x-6 sm:grid-cols-2">{rows.map(([label,value])=><div key={label} className="flex min-w-0 items-baseline justify-between gap-4 border-b border-slate-100 py-2.5 text-xs"><dt className="text-slate-500">{label}</dt><dd className="qe-figure text-right font-semibold text-slate-800">{value}</dd></div>)}</dl></div>;
}

export function ReportDetails({ result }: { result: BacktestResult }) {
  const summary = result.summary;
  const tradeRows: Array<[string,string]> = [["Winners / losers / breakeven", `${summary.winningTrades} / ${summary.losingTrades} / ${summary.breakevenTrades}`], ["Best trade", formatCurrency(summary.bestTrade)], ["Worst trade", formatCurrency(summary.worstTrade)], ["Expectancy per trade", formatCurrency(summary.expectancy)], ["Risk / reward", formatNumber(summary.riskReward)], ["Consecutive wins / losses", `${summary.consecutiveWins} / ${summary.consecutiveLosses}`], ["Average holding period", summary.averageHoldingDays === null ? "N/A" : `${formatNumber(summary.averageHoldingDays,1)} days`], ["Session exposure", formatPct(summary.exposurePct)]];
  const riskRows: Array<[string,string]> = [["Maximum drawdown", `${formatPct(summary.maxDrawdownPct)} · ${formatCurrency(summary.maxDrawdownInr)}`], ["Peak date", summary.drawdownPeakDate ? formatDate(summary.drawdownPeakDate) : "N/A"], ["Trough date", summary.drawdownTroughDate ? formatDate(summary.drawdownTroughDate) : "N/A"], ["Recovery", summary.recoveryDate ? formatDate(summary.recoveryDate) : summary.drawdownPeakDate ? "Not recovered" : "N/A"], ["Drawdown duration", `${summary.drawdownDurationDays} days`], ["Longest recovery / ongoing", `${summary.longestRecoveryDays} days`]];
  return <section className="space-y-3" aria-label="Detailed report assumptions">
    <details className="qe-card overflow-hidden"><summary className="flex list-none items-center justify-between gap-4 px-5 py-4 font-bold text-slate-800 marker:content-none sm:px-6"><span>Detailed performance & risk analytics</span><span className="qe-pill">Expand</span></summary><div className="space-y-6 border-t border-slate-100 px-5 py-5 sm:px-6"><DetailGroup title="Trade analytics" rows={tradeRows}/><DetailGroup title="Drawdown episode" rows={riskRows}/></div></details>
    <details className="qe-card overflow-hidden"><summary className="flex list-none items-center justify-between gap-4 px-5 py-4 font-bold text-slate-800 marker:content-none sm:px-6"><span>Configuration & data provenance</span><span className={result.isSynthetic ? "qe-pill qe-pill-demo" : "qe-pill qe-pill-live"}>{result.isSynthetic ? "Demo" : "Historical"}</span></summary><div className="space-y-4 border-t border-slate-100 px-5 py-5 text-xs leading-5 text-slate-600 sm:px-6"><div className="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><p><strong className="text-slate-800">Provider:</strong> {result.provenance?.provider ?? "N/A"}</p><p><strong className="text-slate-800">Dataset:</strong> {result.provenance?.exchange} · daily · {result.provenance?.barCount} bars</p><p><strong className="text-slate-800">Requested:</strong> {result.settings.startDate} — {result.settings.endDate}</p><p><strong className="text-slate-800">Available:</strong> {result.provenance?.actualStart} — {result.provenance?.actualEnd}</p><p className="sm:col-span-2"><strong className="text-slate-800">Adjustment policy:</strong> {result.provenance?.adjustmentPolicy}</p><p className="break-all sm:col-span-2"><strong className="text-slate-800">Data fingerprint:</strong> <span className="font-mono">{result.provenance?.dataHash}</span></p></div><p>{COST_PRESETS[result.settings.costs?.preset ?? "ZERO"]} · Slippage {result.settings.costs?.slippagePct ?? 0}% per side · Risk-free rate {result.settings.riskFreeRatePct ?? 0}%.</p><details><summary className="font-semibold text-slate-700">Raw configuration</summary><pre className="qe-scrollbar mt-3 max-h-64 overflow-auto rounded-xl bg-[var(--qe-navy-950)] p-4 text-[11px] text-slate-200">{JSON.stringify(result.settings,null,2)}</pre></details></div></details>
    <p className="px-1 text-[11px] leading-5 text-slate-500">Backtested performance does not guarantee future results. N/A indicates a mathematically undefined metric. Review Methodology for execution and data limitations.</p>
  </section>;
}
